### ISSUE TITLE
polymer / / => We can run without it.

### ISSUE THREAD

**Issue by codebyuma** [codebyuma/layoutlasso#11]

**Comment by sunilunka** [comment]
Put polymer on the back-burner at the moment, as not sure it is what we need. Will continue to investigate, as discussed on Wednesday the 25/11.

**Comment by sunilunka** [comment]
Got a basic directive working for each element so that it's child (their 'html' inside our widget) can be modified. Have initial construct that should allow them to modify multiple widget children as well. Will test and adjust tomorrow. Need to also construct another potential directive to allow user to style the element(s) and apply changes on click (bonus - in near-realtime, reckon it can be done.) to all elements in the modification array.
